# dhcpcd configuration
# Request domain name (option 15) and domain search list (option 119)
option domain_name, domain_name_servers, domain_search

# Use the received domain name and search list in resolv.conf
require dhcp_domain_name

# Allow only one DNS server entry per interface
nooption rapid_commit
