"""
Render /data/apps/<id>/config.env from manifest config[] + user values.

Format is systemd's EnvironmentFile syntax: KEY=VALUE per line, double
quotes for values containing whitespace or shell-significant chars.
"""

from app.models.app_install import InstalledApp


def generate(app: InstalledApp) -> str:
    lines = [
        "# Auto-generated by gateway-admin — do not edit by hand.",
        f"# App: {app.id} v{app.version}",
        "",
    ]
    for field in app.manifest.config:
        value = app.config_values.get(field.key, field.default)
        if value is None:
            continue
        lines.append(f"{field.key}={_format(value)}")
    return "\n".join(lines) + "\n"


def _format(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    s = str(value)
    if not s:
        return '""'
    if any(c in s for c in '"\\$\n \t#'):
        escaped = s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
        return f'"{escaped}"'
    return s
